# Generated by Django 5.1.6 on 2025-03-07 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_machine_status"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("performance", models.FloatField()),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.machine"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("technician", "Technician"),
                            ("operator", "Operator"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("id_number", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="machine",
            name="Manufacturer",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="Machine",
        ),
        migrations.RemoveField(
            model_name="purchasehistory",
            name="Machine",
        ),
        migrations.DeleteModel(
            name="ProductionSummary",
        ),
        migrations.DeleteModel(
            name="Maintenance",
        ),
        migrations.DeleteModel(
            name="Machine",
        ),
        migrations.DeleteModel(
            name="PurchaseHistory",
        ),
    ]
