# Generated by Django 5.1.6 on 2025-03-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_performance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performance",
            name="performance",
        ),
        migrations.AddField(
            model_name="performance",
            name="downtime",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="performance",
            name="efficiency",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="performance",
            name="uptime",
            field=models.FloatField(default=0.0),
        ),
    ]
