# Generated by Django 5.1.6 on 2025-03-10 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0007_remove_performance_performance_performance_downtime_and_more",
        ),
        (
            "core",
            "0004_rename_maintenance_end_time_machine_last_maintenance_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="machine",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.machine"
            ),
        ),
    ]
