# Generated by Django 5.1.6 on 2025-03-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="maintenance_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="maintenance_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Scheduled for Maintenance", "Scheduled for Maintenance"),
                    ("Under Maintenance", "Under Maintenance"),
                ],
                default="Available",
                max_length=30,
            ),
        ),
    ]
