# Generated by Django 5.1.6 on 2025-03-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_machine_maintenance_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="MaintenanceEnd",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="MaintenanceStart",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
