# Generated by Django 5.1.6 on 2025-03-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_maintenance_maintenanceend_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="machine",
            old_name="maintenance_end_time",
            new_name="last_maintenance_date",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="maintenance_start_time",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="type",
        ),
        migrations.AddField(
            model_name="machine",
            name="downtime_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("In Use", "In Use"),
                    ("Under Maintenance", "Under Maintenance"),
                ],
                default="Available",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="MaintenanceDate",
            field=models.DateField(auto_now_add=True),
        ),
    ]
